### ISSUE TITLE
Feature query: Custom function to represent numerical data in human readable form

### ISSUE THREAD

**Issue by answerquest** [koalyptus/HTML-Table-Filter-Generator#5]
In case the cell content is a number, and if it's larger than say 1000, I want to run a custom function that will replace it with a more human-readable string. Simple as this:

```
function easynumber(N) {
    F = parseFloat(N);
    if (!F) return N;
    else if(F >= 10000000 ) return F/10000000 + " crore";
    else if(F >= 100000 ) return F/100000 + " lakh";
    else if(F >= 1000 ) return F/1000 + " thousand";
    else if(F >= 0) return N;
}
```

Can you give any pointers to where I can place this in the tablefilter script, so that it intercepts anything being printed, or do you think this function could be passed as an option?
At present this simplistic function would probably mess up strings that begin with numbers greater than 999, but with a little tweaking I'm sure that can be overcome as well. I don't have such instances in my data since any part having such a number is bound to have it comma separated.
We still want to keep the numbers in original form internally, so that the numerical comparison operators work.

**Comment by koalyptus** [comment]
From what I understand, you'd like to conditionally format a cell based on its value. You shouldn't modify the Table Filter script to do so or pass any function. Just do your formatting operation on the table just after being rendered and before instanciating TF and then assign the correct data type in the configuration object. Here some examples:
http://tablefilter.free.fr/demos.php?1=col_number_format

**Comment by answerquest** [comment]
Thanks, and apologies for not replying earlier. I'd like to keep the `values` intact as numbers so that comparative etc operations can be done on them. Only display needs to be altered. Not understanding how to do with the proposed way, because that would then alter the values being passed o tablefilter, hence ruling out its numerical comparison etc features.

**Comment by koalyptus** [comment]
From what I understand you imply there is a 'label' (ie formatted number) and a 'value' associated with a cell. In reality there is only a 'text' in a cell and then based on the column type the script will internally convert that text into a number for example. Please refer to link in my previous comment. Also you might consider custom_cell_data delegate too.
