### ISSUE TITLE
External download button for filtered table

### ISSUE THREAD

**Issue by ghost** [koalyptus/HTML-Table-Filter-Generator#8]
Hi, I am curious:
Is there a way to put a download button externally to the table, such that the result of any filtering and selection can be stored in a csv/text/xls file?
Dylan

**Comment by koalyptus** [comment]
Hi Dylan,
HTFG does not come with a built-in export functionality, but it could be comfortably implemented by using the public API to get the filtered data (`GetFilteredData` method) and pass it to one of the many js libraries specialising in exporting data to csv/text/xls.

**Comment by ghost** [comment]
Thanks, this is a bit beyond immediate ability. I will look into it.

**Comment by koalyptus** [comment]
No worries. If you are thinking about using this widget I advise you to switch to [https://github.com/koalyptus/TableFilter](TableFilter).
Cheers
